### ISSUE TITLE
Unnecessary copy of blas_matrix?

### ISSUE THREAD

**Issue by leofang** [ALPSCore/CT-HYB-SEGMENT#10]
In [line 214 of hybmatrix.cpp](https://github.com/ALPSCore/CT-HYB-SEGMENT/blob/fd6aca4976ed959ace7a1e0a50d4db1a589d9a91/hybmatrix.cpp#L214), the base object (bias_matrix) is copy-constructed as "bup". However, in the subsequent lines this bup object was never used; it is "this", which points to a derived object (hybmatrix), getting rebuilt. At the end of this function call, the bup object is destroyed. 

Based on a few quick tests, I think killing line 214 can gain about 1% efficiency (acceptance rate of removing an antisegment times about 0.3~0.5, as creating and destroying a blas_matrix object involves memory allocation, which is expensive). While it's probably not particularly appealing to you, I post it anyway as it's just a quick fix. Let me know if I'm wrong.

ps. I did the test on the old version of this code that came with ALPS, not the ALPSCore one, so it might be slightly different.

**Comment by egull** [comment]
No, this sounds reasonable. Those blas_classes are terrible.

Can you fix it and put a pull request?

Emanuel
