### ISSUE TITLE
Compile problem: boost config.h linking to mpi.h

### ISSUE THREAD

**Issue by henhans** [ALPSCore/CT-HYB-SEGMENT#5]
Dear Dr. Antipov,

I'm trying to compile the cthyb code, but it shows the following error, which seems to be the problem between boost and mpi. I'm wondering how to solve this problem? Thank you!

Scanning dependencies of target alps_hyb_exp
[  8%] Building CXX object CMakeFiles/alps_hyb_exp.dir/hybsim.cpp.o
In file included from /usr/include/boost/mpi/allocator.hpp(15),
                 from /usr/include/boost/mpi.hpp(22),
                 from /usr/local/include/alps/utilities/boost_mpi.hpp(13),
                 from /usr/local/include/alps/accumulators/mpi.hpp(16),
                 from /usr/local/include/alps/accumulators/feature.hpp(22),
                 from /usr/local/include/alps/accumulators/feature/mean.hpp(12),
                 from /usr/local/include/alps/accumulators/wrappers.hpp(12),
                 from /usr/local/include/alps/accumulators/accumulator.hpp(13),
                 from /usr/local/include/alps/accumulators.hpp(10),
                 from /usr/local/include/alps/mc/mcbase.hpp(12),
                 from /home/thlee/alps-cthyb/hyb.hpp(31),
                 from /home/thlee/alps-cthyb/hybsim.cpp(35):
/usr/include/boost/mpi/config.hpp(20): catastrophic error: cannot open source file "mpi.h"
  #include <mpi.h>
                  ^

compilation aborted for /home/thlee/alps-cthyb/hybsim.cpp (code 4)
make[2]: **\* [CMakeFiles/alps_hyb_exp.dir/hybsim.cpp.o] Error 4
make[1]: **\* [CMakeFiles/alps_hyb_exp.dir/all] Error 2
make: **\* [all] Error 2

**Comment by aeantipov** [comment]
Hi Tsung-Tan,

Check if the alpscore has MPI enabled and that the tests are running.

**Comment by henhans** [comment]
Dear Dr. Antipov,

I'm wondering which file should I modify to enable MPI?  I've passed all the make test in ALPSCore. Thank you!

**Comment by aeantipov** [comment]
If you built it yourself (without a package manager) - go to the build dir and type `ccmake .` - you will see the ENABLE_MPI flag. Check that it is on.

**Comment by henhans** [comment]
The ENABLE_MPI flag is on, and the the ALPSCore make tests are all passed, but it still shows the same error: /usr/include/boost/mpi/config.hpp(20): catastrophic error: cannot open source file "mpi.h", while compiling...Would that be boost problem?

**Comment by aeantipov** [comment]
Not sure, if alpscore compiles and all tests run (including mpi tests) - then no. 
One other thing is that ALPSCore may not export the MPI include (it is a bug then). 
Try adding "CXX=mpic++ cmake ..." for compiling alps_cthyb. (here mpic++ is your mpi c++ compiler).

**Comment by henhans** [comment]
After trying "CXX=mpic++ cmake .." It shows the following error:

Scanning dependencies of target alps_hyb_exp
[  8%] Building CXX object CMakeFiles/alps_hyb_exp.dir/hybsim.cpp.o
/usr/include/c++/4.8/bits/stl_iterator_base_types.h(165): error: class "alps::params_ns::option_type" has no member "iterator_category"
        typedef typename _Iterator::iterator_category iterator_category;
                                    ^
          detected during:
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=alps::params_ns::params::mapped_type]" at line 1249 of "/usr/include/c++/4.8/bits/stl_vector.h"
            instantiation of "void std::vector<_Tp, _Alloc>::_M_assign_dispatch(_InputIterator, _InputIterator, std::__false_type) [with _Tp=double, _Alloc=std::allocator<double>, _InputIterator=alps::params_ns::params::mapped_type]" at line 507 of "/usr/include/c++/4.8/bits/stl_vector.h"
            instantiation of "void std::vector<_Tp, _Alloc>::assign(_InputIterator, _InputIterator) [with _Tp=double, _Alloc=std::allocator<double>, _InputIterator=alps::params_ns::params::mapped_type]" at line 64 of "/home/thlee/alps-cthyb/hybint.hpp"

/usr/include/c++/4.8/bits/stl_iterator_base_types.h(166): error: class "alps::params_ns::option_type" has no member "value_type"
        typedef typename _Iterator::value_type        value_type;
                                    ^
          detected during:
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=alps::params_ns::params::mapped_type]" at line 1249 of "/usr/include/c++/4.8/bits/stl_vector.h"
            instantiation of "void std::vector<_Tp, _Alloc>::_M_assign_dispatch(_InputIterator, _InputIterator, std::__false_type) [with _Tp=double, _Alloc=std::allocator<double>, _InputIterator=alps::params_ns::params::mapped_type]" at line 507 of "/usr/include/c++/4.8/bits/stl_vector.h"
            instantiation of "void std::vector<_Tp, _Alloc>::assign(_InputIterator, _InputIterator) [with _Tp=double, _Alloc=std::allocator<double>, _InputIterator=alps::params_ns::params::mapped_type]" at line 64 of "/home/thlee/alps-cthyb/hybint.hpp"

/usr/include/c++/4.8/bits/stl_iterator_base_types.h(167): error: class "alps::params_ns::option_type" has no member "difference_type"
        typedef typename _Iterator::difference_type   difference_type;
                                    ^
          detected during:
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=alps::params_ns::params::mapped_type]" at line 1249 of "/usr/include/c++/4.8/bits/stl_vector.h"
            instantiation of "void std::vector<_Tp, _Alloc>::_M_assign_dispatch(_InputIterator, _InputIterator, std::__false_type) [with _Tp=double, _Alloc=std::allocator<double>, _InputIterator=alps::params_ns::params::mapped_type]" at line 507 of "/usr/include/c++/4.8/bits/stl_vector.h"
            instantiation of "void std::vector<_Tp, _Alloc>::assign(_InputIterator, _InputIterator) [with _Tp=double, _Alloc=std::allocator<double>, _InputIterator=alps::params_ns::params::mapped_type]" at line 64 of "/home/thlee/alps-cthyb/hybint.hpp"

/usr/include/c++/4.8/bits/stl_iterator_base_types.h(168): error: class "alps::params_ns::option_type" has no member "pointer"
        typedef typename _Iterator::pointer           pointer;
                                    ^
          detected during:
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=alps::params_ns::params::mapped_type]" at line 1249 of "/usr/include/c++/4.8/bits/stl_vector.h"
            instantiation of "void std::vector<_Tp, _Alloc>::_M_assign_dispatch(_InputIterator, _InputIterator, std::__false_type) [with _Tp=double, _Alloc=std::allocator<double>, _InputIterator=alps::params_ns::params::mapped_type]" at line 507 of "/usr/include/c++/4.8/bits/stl_vector.h"
            instantiation of "void std::vector<_Tp, _Alloc>::assign(_InputIterator, _InputIterator) [with _Tp=double, _Alloc=std::allocator<double>, _InputIterator=alps::params_ns::params::mapped_type]" at line 64 of "/home/thlee/alps-cthyb/hybint.hpp"

/usr/include/c++/4.8/bits/stl_iterator_base_types.h(169): error: class "alps::params_ns::option_type" has no member "reference"
        typedef typename _Iterator::reference         reference;
                                    ^
          detected during:
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=alps::params_ns::params::mapped_type]" at line 1249 of "/usr/include/c++/4.8/bits/stl_vector.h"
            instantiation of "void std::vector<_Tp, _Alloc>::_M_assign_dispatch(_InputIterator, _InputIterator, std::__false_type) [with _Tp=double, _Alloc=std::allocator<double>, _InputIterator=alps::params_ns::params::mapped_type]" at line 507 of "/usr/include/c++/4.8/bits/stl_vector.h"
            instantiation of "void std::vector<_Tp, _Alloc>::assign(_InputIterator, _InputIterator) [with _Tp=double, _Alloc=std::allocator<double>, _InputIterator=alps::params_ns::params::mapped_type]" at line 64 of "/home/thlee/alps-cthyb/hybint.hpp"

compilation aborted for /home/thlee/alps-cthyb/hybsim.cpp (code 2)
make[2]: **\* [CMakeFiles/alps_hyb_exp.dir/hybsim.cpp.o] Error 2
make[1]: **\* [CMakeFiles/alps_hyb_exp.dir/all] Error 2
make: **\* [all] Error 2

**Comment by aeantipov** [comment]
I see, well then it won't work so easy. 
Where is your mpi installed? Is it some /usr/local path or something else?

**Comment by henhans** [comment]
Yes. I install it using package manager. it locates at /usr/lib/...

**Comment by aeantipov** [comment]
I see, so it seems there is a bug in alpscore exporting mpi (at present no clear way of how to circumvent it). 
One thing to do, is to remove "CXX=..." and try compiling the code with `make VERBOSE=1`. It will fail, as before, but you can see which command is used to compile the code, i.e. smth like /usr/bin/mpic++ -O3 -DNDEBUG -I...". Compare it then with the analogous compilation of alpscore tests and see what is the difference.

**Comment by henhans** [comment]
Dear Dr. Antipov,

This problem is solved by adding following line in CMakeLists.txt:
find_package(MPI)
include_directories(SYSTEM ${MPI_INCLUDE_PATH})
Thanks for your help!
Tsung-Han

**Comment by aeantipov** [comment]
Great to see that!
